spring:
  datasource:
    url: jdbc:mysql://47.98.61.53:3306/ad?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: remote_user
    password: Fengkefeng666!
    driver-class-name: com.mysql.jdbc.Driver # 注意不要用 cj.jdbc.Driver（适用于 MySQL 8+）
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.AndroidServer.model
server:
  port: 8081
logging:
  level:
    com.example.AndroidServer.mapper.UserMapper: DEBUG