spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stray?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver # 注意不要用 cj.jdbc.Driver（适用于 MySQL 8+）
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.AndroidServer.model
server:
  port: 8081